# fly.toml - Fly.io configuration for your Telegram bot

app = "apmywinv2"  # your app name, lowercase letters and dashes only

# Environment variables can be set via Fly secrets, not here
# [env]
# BOT_TOKEN should be set with: fly secrets set BOT_TOKEN="your-telegram-bot-token"

# Define worker process
[processes]
worker = "python main.py"
